language: node_js
node_js: 14.17.3
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: angular-project-11
  api_key:
    secure: j4GNGhd53Cv34x0D4bqZQEo8vuezXd5ilSded1PaXmsipj5cWFZnOfezUCvKj6Q516pq8TzbjZ2qyJEtGGkKHVd86zmo3G2QYtsAepjca528+Ux++pxjV7w5SGLqfbRe6SOJwjJtJ4Jc92XJ/Yt9G1zzNl5Vy73vm07F8q1nl9nIloWSsn4xHZZwopJgYX23mmImjQzR5UYsnPI/GvFjP0u+yKhE1Ij+ruREx4mfs+Pl59yk6kZGbmYCaRvRWl1TNc1qPE3VpueixvohtllM5eVL3XsxjpuyzRpgM5wkp8Q0eTEC/jtholQyr9fNg0f5vKeN7aFtKQK4BDa/PXR45ZsBqYelq6BeKsvjfiw9NMNIkauhpKCRNW1t0mq4f/dIEuzUCLQtd34kfWPZwf5/o2Tv/CMIvHJurx+JypP/2sYhPwp5jRith2G6r4HrSbNn7BOjiyzyvVxMBh8mPsFEKgr7VKEm6z5bm9GO35bEWwHghcjpVp0JMva9HfZ1jDBJlpZiOveIK4HmzIu9VHes0tRHb/cusfmdUYO1bUy5q6Blm+aioGRzggEcFimkcH6tUlVUBNsMa995vytcaKdxG7nCWJADz0wRkZ4LnfqEOHTm+e5NOZqXKHSM/ppcXVrAkKsXCoTR92H4ks4GSuRwvHXY1xMVPu+wzr9LZ2Pu6BY=
