language: node_js
node_js: 14.17.3
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Op9r/m8jyxpT33VayLr/EMg8yvn79N+Hqdmcdt+lzkNe0HwWM0CogDvEDBoYu+rX0cW2EXW/47Vt3UxYvVDpQPM5o6Eli1hkAgQwFaRZbwejQg7XXof9rWzknstC+NFBPZ69QvtXb4VHqn776zb9VN9jcSNso1baQ/gPxOrL1pAROtai+QrLrVdRWD+sr29RMvPWF9WxaCwlt+OEiKy7HG8l8pHowWHqoEc8R6V1Ag63SPtd40UGOD0XWsYwcB/XEEoaTj9+XbwiyG4+XHpeSOKZMbiVIEXz8/4/xk2iO+8KNiLWxjueh1KiNhKOaQj3nUVOVGvSthLUQ96y70EvczwxE3GdyEj7CU8RZaUSdrD5Kk4ZT+6x3+zrVFZ0zWUmGunm6lKMKK+xzV5iSGouPsXX0HLEQwNOg1jBLzk1l6d2n/lGgW4NxRUwKtkqR5NxLQozmPSjO3+1oLf41fwaxpaeL06sKNX2c4jeiWtxgDic17C1fgDX6QLzzkC4zVOQCsowCYHQW4O05y+B0KA7Eb/j+oRVvaeTO0orfOhpSjt9UesQw5ZxZF5hATkDE+/RIkZd/nv6vtsOFLjSYDqPi4zQGHfmaH2WCv4E8SECgB9rB2YSaiZkilrxIjWVW73JDdYKVwZZRJFCashCJpNC9A6IhZzWHZjUfsGs7+9tG8I=
  app: angular
  on:
    repo: Sanny232/angular
    branch: master
  skip_cleanup: 'true'
